-- Run against LOCAL Supabase after migration 16 has been applied by the operator.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path=public,extensions;
SELECT no_plan();
INSERT INTO auth.users(id,email) VALUES ('ec150000-0000-4000-8000-000000000001','application-reviewer@qa.example'),('ec150000-0000-4000-8000-000000000002','application-tenant@qa.example');
INSERT INTO platform_admins(user_id) VALUES ('ec150000-0000-4000-8000-000000000001');
SELECT ok(NOT has_table_privilege('anon','public.restaurant_applications','SELECT'),'Anonymous cannot read applications');
SELECT ok(NOT has_table_privilege('anon','public.restaurant_applications','INSERT'),'Anonymous cannot insert directly');
SELECT ok(NOT has_function_privilege('anon','public.submit_restaurant_application(jsonb)','EXECUTE'),'Anonymous cannot bypass server submission endpoint');
SELECT ok(NOT has_function_privilege('authenticated','public.submit_restaurant_application(jsonb)','EXECUTE'),'Authenticated tenants cannot bypass server endpoint');
SET LOCAL ROLE service_role;
SELECT lives_ok($$SELECT public.submit_restaurant_application('{"kind":"application","full_name":"Applicant","business_name":"Application QA","email":"application@qa.example","phone":"0501234567","city":"Nazareth","business_type":"cafe","branch_count":2,"requested_plan_code":"pro","message":"QA","locale":"en"}')$$,'Server can submit valid application');
SELECT lives_ok($$SELECT public.submit_restaurant_application('{"kind":"application","full_name":"Applicant","business_name":"Application QA","email":"application@qa.example","phone":"0501234567","city":"Nazareth","business_type":"cafe","branch_count":2,"requested_plan_code":"pro","message":"Duplicate","locale":"en"}')$$,'Pending retry is idempotent');
RESET ROLE;
SELECT is((SELECT count(*)::integer FROM restaurant_applications WHERE email='application@qa.example'),1,'One pending request');
SELECT is((SELECT message FROM restaurant_applications WHERE email='application@qa.example'),'QA','Retry does not overwrite request');
SELECT throws_ok($$SELECT public.submit_restaurant_application('{"kind":"application","full_name":"Applicant","business_name":"Invalid","email":"invalid@qa.example","phone":"0501234567","city":"Nazareth","business_type":"cafe","branch_count":0,"locale":"en"}')$$,'23514',NULL,'Database validates branch count');
CREATE TEMP TABLE application_test_id AS SELECT id FROM restaurant_applications WHERE email='application@qa.example';
GRANT SELECT ON application_test_id TO authenticated;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','ec150000-0000-4000-8000-000000000002',true);
SELECT is((SELECT count(*)::integer FROM restaurant_applications),0,'Ordinary user cannot see applications');
SELECT throws_ok($$SELECT public.review_restaurant_application((SELECT id FROM application_test_id),'approved','Unauthorized','pro')$$,'42501','forbidden','Tenant cannot approve');
SELECT set_config('request.jwt.claim.sub','ec150000-0000-4000-8000-000000000001',true);
SELECT is((SELECT count(*)::integer FROM restaurant_applications WHERE id IN (SELECT id FROM application_test_id)),1,'Platform admin can list and view');
SELECT lives_ok($$SELECT public.review_restaurant_application((SELECT id FROM application_test_id),'approved','Checked','business')$$,'Platform admin approves and changes plan');
SELECT ok((SELECT status='approved' AND reviewed_by=auth.uid() AND reviewed_at IS NOT NULL AND requested_plan_code='business' FROM restaurant_applications WHERE id IN (SELECT id FROM application_test_id)),'Decision records reviewer, time and plan');
SELECT throws_ok($$SELECT public.review_restaurant_application((SELECT id FROM application_test_id),'rejected','Second review',NULL)$$,'40001','already_reviewed_or_missing','Duplicate review cannot overwrite decision');
RESET ROLE;
INSERT INTO restaurant_applications(kind,full_name,business_name,email,phone,city,business_type,branch_count,locale) VALUES ('application','Reject QA','Reject QA','reject@qa.example','0501234567','Nazareth','restaurant',1,'he');
UPDATE application_test_id SET id=(SELECT id FROM restaurant_applications WHERE email='reject@qa.example');
SET LOCAL ROLE authenticated;
SELECT lives_ok($$SELECT public.review_restaurant_application((SELECT id FROM application_test_id),'rejected','Not suitable',NULL)$$,'Platform admin can reject');
SELECT is((SELECT status FROM restaurant_applications WHERE id IN (SELECT id FROM application_test_id)),'rejected','Rejection persists');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
