-- Requires operator-applied migration 14. Tests roll back all local fixture changes.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path=public,extensions;
SELECT no_plan();
INSERT INTO auth.users(id,email) VALUES('ec000000-0000-4000-8000-000000000001','launch-owner@db.example'),('ec000000-0000-4000-8000-000000000002','launch-staff@db.example');
INSERT INTO memberships(user_id,business_id,role) VALUES('ec000000-0000-4000-8000-000000000001','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','owner'),('ec000000-0000-4000-8000-000000000002','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','staff');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','ec000000-0000-4000-8000-000000000001',true);
SELECT lives_ok($$SELECT set_restaurant_launch('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',true)$$,'Owner publishes');
SELECT lives_ok($$SELECT manage_business_domain('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','menu.fixture.org','register')$$,'Owner registers DNS name');
SELECT throws_ok($$SELECT manage_business_domain('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','foreign.fixture.org','register')$$,'42501','forbidden','Foreign tenant denied');
SELECT throws_ok($$SELECT manage_business_domain('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','menu.fixture.org','activate')$$,'P0001','unverified','Unverified domain cannot activate');
SELECT throws_ok($$SELECT verify_business_domain(gen_random_uuid(),'bad')$$,'42501',NULL,'Owner cannot forge DNS verification');
RESET ROLE;
SELECT ok(NOT verify_business_domain((SELECT id FROM business_domains WHERE hostname='menu.fixture.org'),'bad'),'Wrong challenge cannot verify');
SELECT ok(verify_business_domain((SELECT id FROM business_domains WHERE hostname='menu.fixture.org'),(SELECT verification_token FROM business_domains WHERE hostname='menu.fixture.org')),'Verified DNS service completes exact challenge');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','ec000000-0000-4000-8000-000000000001',true);
SELECT lives_ok($$SELECT manage_business_domain('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','menu.fixture.org','canonical')$$,'Verified domain activated as canonical');
SELECT is(resolve_restaurant_host('menu.fixture.org'),'darb-bistro','Host resolves exact owner');
SELECT is(resolve_restaurant_host('other.fixture.org'),NULL::text,'Unknown hostname does not fallback to a tenant');
SELECT lives_ok($$SELECT set_restaurant_launch('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',false)$$,'Unpublish succeeds');
SELECT is(resolve_restaurant_host('menu.fixture.org'),NULL::text,'Unpublish immediately stops domain resolution');
SELECT lives_ok($$SELECT set_restaurant_launch('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',true)$$,'Republish');
SELECT lives_ok($$SELECT manage_business_domain('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','menu.fixture.org','deactivate')$$,'Deactivate');
SELECT is(resolve_restaurant_host('menu.fixture.org'),NULL::text,'Inactive hostname cannot resolve');
SELECT set_config('request.jwt.claim.sub','ec000000-0000-4000-8000-000000000002',true);
SELECT throws_ok($$SELECT set_restaurant_launch('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',true)$$,'42501','forbidden','Staff cannot publish');
SELECT is((SELECT count(*)::integer FROM business_domains),0,'Staff cannot read ownership challenges');
RESET ROLE;
SELECT ok(bool_and(consume_public_budget(repeat('a',64)))) FROM generate_series(1,60);
SELECT ok(NOT consume_public_budget(repeat('a',64)),'Distributed budget rejects request 61');
UPDATE business_domains SET active=true,verified_until=now()-interval '1 second' WHERE hostname='menu.fixture.org';
SELECT is(resolve_restaurant_host('menu.fixture.org'),NULL::text,'Expired ownership proof fails closed');
SELECT set_config('request.jwt.claim.sub','ec000000-0000-4000-8000-000000000001',true);
SELECT set_restaurant_launch('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',false);
SELECT is(jsonb_array_length(restaurant_sitemap('darb-bistro',0)),0,'Unpublished restaurant excluded from sitemap');
SELECT set_restaurant_launch('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',true);
SELECT ok(jsonb_array_length(restaurant_sitemap('darb-bistro',0))>0,'Published assigned menu branches enter sitemap');
SELECT * FROM finish();
ROLLBACK;
