BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path=public,extensions;
SELECT no_plan();
INSERT INTO auth.users(id,email) VALUES ('ec900000-0000-4000-8000-000000000001','platform-local@qa.example'),('ec900000-0000-4000-8000-000000000002','member-local@qa.example');
INSERT INTO platform_admins(user_id) VALUES ('ec900000-0000-4000-8000-000000000001');
INSERT INTO memberships(user_id,business_id,role) VALUES ('ec900000-0000-4000-8000-000000000002','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','staff');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','ec900000-0000-4000-8000-000000000001',true);
SELECT ok(is_platform_admin(),'Platform privilege resolves independently of memberships');
SELECT is((SELECT count(*)::integer FROM memberships WHERE user_id=auth.uid()),0,'Platform user needs no membership');
SELECT is((SELECT count(*)::integer FROM businesses WHERE id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),1,'Platform can read unrelated business');
SELECT lives_ok($$UPDATE businesses SET status='suspended' WHERE id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'$$,'Platform can suspend');
SELECT is((SELECT status FROM businesses WHERE id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),'suspended','Suspension persisted');
SELECT lives_ok($$UPDATE businesses SET status='active' WHERE id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'$$,'Platform can activate');
SELECT lives_ok($$INSERT INTO business_feature_overrides(business_id,feature_key,enabled,reason) VALUES('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','custom_domains',true,'Local rollback test') ON CONFLICT(business_id,feature_key) DO UPDATE SET enabled=true$$,'Platform can manage overrides');
SELECT ok((SELECT count(*) FROM profiles)>1,'Platform can count user profiles');
SELECT set_config('request.jwt.claim.sub','ec900000-0000-4000-8000-000000000002',true);
SELECT ok(NOT is_platform_admin(),'Staff is not a platform admin');
SELECT is((SELECT count(*)::integer FROM platform_admins),0,'Staff cannot read platform role records');
SELECT is((SELECT count(*)::integer FROM businesses WHERE id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),0,'Staff remains tenant isolated');
SELECT throws_ok($$INSERT INTO business_feature_overrides(business_id,feature_key,enabled) VALUES('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','custom_branding',true)$$,'42501',NULL,'Staff cannot write foreign overrides');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
